// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: misinformation_group.
// - Entity ID: 102019a1d99a4037723989b9845367fe02b.
// - Entity Version: 102019a1dbcbce7723a8fcbc902bf548690.
// - Task ID: 68fd5f5b822475ee4330a749.
// - Task Root ID: 68fd5593b7797f696b910611.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for MisinformationGroupModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface MisinformationGroupModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  false_statement_text: string;
  false_statement_text_hash: string;
  user_ids: string[];
  verification_result_id: string;
}

/**
 * ORM class for MisinformationGroup entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class MisinformationGroupORM {
  private static instance: MisinformationGroupORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1d99a4037723989b9845367fe02b';
    this.entityName = 'misinformation_group';
    this.entityVersion = '102019a1dbcbce7723a8fcbc902bf548690';
    this.taskId = '68fd5f5b822475ee4330a749';
    this.taskRootId = '68fd5593b7797f696b910611';
  }

  /**
   * Get singleton instance of MisinformationGroupORM
   */
  public static getInstance(): MisinformationGroupORM {
    if (!MisinformationGroupORM.instance) {
      MisinformationGroupORM.instance = new MisinformationGroupORM();
    }
    
    return MisinformationGroupORM.instance;
  }

  /**
   * Get all MisinformationGroup records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllMisinformationGroup(): Promise<MisinformationGroupModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new MisinformationGroup record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertMisinformationGroup(data: MisinformationGroupModel[]): Promise<MisinformationGroupModel[]> {
    const structured = data.map((item) => CreateData(MisinformationGroupModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all MisinformationGroup records
   */
  async purgeAllMisinformationGroup(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List MisinformationGroup records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listMisinformationGroup(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[MisinformationGroupModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get misinformation_group by Id index
   * This function gets data by index.
   */
  async getMisinformationGroupById(
    id: string,
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) misinformation_group by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMisinformationGroupById(
    id: string,
    data: MisinformationGroupModel
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexId(
      id
    );

    const values = MisinformationGroupModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete misinformation_group by Id index
   */
  async deleteMisinformationGroupById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get misinformation_group by DataCreator index
   * This function gets data by index.
   */
  async getMisinformationGroupByDataCreator(
    data_creator: string,
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) misinformation_group by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMisinformationGroupByDataCreator(
    data_creator: string,
    data: MisinformationGroupModel
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = MisinformationGroupModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete misinformation_group by DataCreator index
   */
  async deleteMisinformationGroupByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get misinformation_group by DataUpdater index
   * This function gets data by index.
   */
  async getMisinformationGroupByDataUpdater(
    data_updater: string,
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) misinformation_group by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMisinformationGroupByDataUpdater(
    data_updater: string,
    data: MisinformationGroupModel
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = MisinformationGroupModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete misinformation_group by DataUpdater index
   */
  async deleteMisinformationGroupByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get misinformation_group by FalseStatementTextHash index
   * This function gets data by index.
   */
  async getMisinformationGroupByFalseStatementTextHash(
    false_statement_text_hash: string,
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexFalseStatementTextHash(
      false_statement_text_hash
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) misinformation_group by FalseStatementTextHash index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMisinformationGroupByFalseStatementTextHash(
    false_statement_text_hash: string,
    data: MisinformationGroupModel
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexFalseStatementTextHash(
      false_statement_text_hash
    );

    const values = MisinformationGroupModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete misinformation_group by FalseStatementTextHash index
   */
  async deleteMisinformationGroupByFalseStatementTextHash(
    false_statement_text_hash: string
  ): Promise<void> {
    const index = createIndexFalseStatementTextHash(
      false_statement_text_hash
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get misinformation_group by VerificationResultId index
   * This function gets data by index.
   */
  async getMisinformationGroupByVerificationResultId(
    verification_result_id: string,
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexVerificationResultId(
      verification_result_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) misinformation_group by VerificationResultId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMisinformationGroupByVerificationResultId(
    verification_result_id: string,
    data: MisinformationGroupModel
  ): Promise<MisinformationGroupModel[]> {
    const index = createIndexVerificationResultId(
      verification_result_id
    );

    const values = MisinformationGroupModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete misinformation_group by VerificationResultId index
   */
  async deleteMisinformationGroupByVerificationResultId(
    verification_result_id: string
  ): Promise<void> {
    const index = createIndexVerificationResultId(
      verification_result_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to MisinformationGroupModel data array
   */
  private resultToData(values: Data[]): MisinformationGroupModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return MisinformationGroupModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as MisinformationGroupModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized MisinformationGroupModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is MisinformationGroupModel => item !== null);
  }
}

/**
 * Convert MisinformationGroupModel data to Value array
 */
function MisinformationGroupModelToValues(data: MisinformationGroupModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'false_statement_text', type: DataType.string, defaultValue: '' },
    { key: 'false_statement_text_hash', type: DataType.string, defaultValue: '' },
    { key: 'user_ids', type: DataType.array, defaultValue: [] },
    { key: 'verification_result_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof MisinformationGroupModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to MisinformationGroupModel data
 */
function MisinformationGroupModelFromValues(values: Value[]): MisinformationGroupModel {
  const data: Partial<MisinformationGroupModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'false_statement_text':
        data.false_statement_text = ParseValue(value, DataType.string) as string;
        break;
      case 'false_statement_text_hash':
        data.false_statement_text_hash = ParseValue(value, DataType.string) as string;
        break;
      case 'user_ids':
        data.user_ids = ParseValue(value, DataType.array) as string[];
        break;
      case 'verification_result_id':
        data.verification_result_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as MisinformationGroupModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for FalseStatementTextHash fields
 */
function createIndexFalseStatementTextHash(
  false_statement_text_hash: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, false_statement_text_hash, 'false_statement_text_hash'),
  ];

  return {
    fields: ['false_statement_text_hash'],
    values
  };
}
/**
 * Create index for VerificationResultId fields
 */
function createIndexVerificationResultId(
  verification_result_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, verification_result_id, 'verification_result_id'),
  ];

  return {
    fields: ['verification_result_id'],
    values
  };
}

export default MisinformationGroupORM;