// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_session.
// - Entity ID: 102019a1d99a40270f6b570e7d1d7dba8ed.
// - Entity Version: 102019a1dbcbce7723a8fcbc902bf548690.
// - Task ID: 68fd5f5b822475ee4330a749.
// - Task Root ID: 68fd5593b7797f696b910611.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserSessionMode
 */
export enum UserSessionMode {
  Unspecified = 0,
  SingleUser = 1,
  MultiUser = 2,
}



/**
 * Interface for UserSessionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserSessionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  mode: UserSessionMode;
  start_time: string;
  end_time?: string | null;
  is_active: boolean;
}

/**
 * ORM class for UserSession entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserSessionORM {
  private static instance: UserSessionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1d99a40270f6b570e7d1d7dba8ed';
    this.entityName = 'user_session';
    this.entityVersion = '102019a1dbcbce7723a8fcbc902bf548690';
    this.taskId = '68fd5f5b822475ee4330a749';
    this.taskRootId = '68fd5593b7797f696b910611';
  }

  /**
   * Get singleton instance of UserSessionORM
   */
  public static getInstance(): UserSessionORM {
    if (!UserSessionORM.instance) {
      UserSessionORM.instance = new UserSessionORM();
    }
    
    return UserSessionORM.instance;
  }

  /**
   * Get all UserSession records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserSession(): Promise<UserSessionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserSession record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserSession(data: UserSessionModel[]): Promise<UserSessionModel[]> {
    const structured = data.map((item) => CreateData(UserSessionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserSession records
   */
  async purgeAllUserSession(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserSession records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserSession(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserSessionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_session by Id index
   * This function gets data by index.
   */
  async getUserSessionById(
    id: string,
  ): Promise<UserSessionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_session by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSessionById(
    id: string,
    data: UserSessionModel
  ): Promise<UserSessionModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_session by Id index
   */
  async deleteUserSessionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_session by DataCreator index
   * This function gets data by index.
   */
  async getUserSessionByDataCreator(
    data_creator: string,
  ): Promise<UserSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_session by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSessionByDataCreator(
    data_creator: string,
    data: UserSessionModel
  ): Promise<UserSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_session by DataCreator index
   */
  async deleteUserSessionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_session by DataUpdater index
   * This function gets data by index.
   */
  async getUserSessionByDataUpdater(
    data_updater: string,
  ): Promise<UserSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_session by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSessionByDataUpdater(
    data_updater: string,
    data: UserSessionModel
  ): Promise<UserSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_session by DataUpdater index
   */
  async deleteUserSessionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_session by IsActive index
   * This function gets data by index.
   */
  async getUserSessionByIsActive(
    is_active: boolean,
  ): Promise<UserSessionModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_session by IsActive index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSessionByIsActive(
    is_active: boolean,
    data: UserSessionModel
  ): Promise<UserSessionModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const values = UserSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_session by IsActive index
   */
  async deleteUserSessionByIsActive(
    is_active: boolean
  ): Promise<void> {
    const index = createIndexIsActive(
      is_active
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserSessionModel data array
   */
  private resultToData(values: Data[]): UserSessionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserSessionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserSessionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserSessionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserSessionModel => item !== null);
  }
}

/**
 * Convert UserSessionModel data to Value array
 */
function UserSessionModelToValues(data: UserSessionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'mode', type: DataType.enumeration, defaultValue: 0 },
    { key: 'start_time', type: DataType.string, defaultValue: '' },
    { key: 'end_time', type: DataType.string, defaultValue: null },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserSessionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserSessionModel data
 */
function UserSessionModelFromValues(values: Value[]): UserSessionModel {
  const data: Partial<UserSessionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'mode':
        data.mode = ParseValue(value, DataType.enumeration) as UserSessionMode;
        break;
      case 'start_time':
        data.start_time = ParseValue(value, DataType.string) as string;
        break;
      case 'end_time':
        data.end_time = ParseValue(value, DataType.string) as string | null;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as UserSessionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for IsActive fields
 */
function createIndexIsActive(
  is_active: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
  ];

  return {
    fields: ['is_active'],
    values
  };
}

export default UserSessionORM;